### ISSUE TITLE
Tommy's Feedback 

### ISSUE THREAD

**Issue by wojtczat** [OpenLiberty/draft-guide-kubernetes#48] opened 2018-09-28 20:46 UTC
Hello, so this guide was very well done. I had no issues understanding any of the content or executing any of the commands being ran in this guide. There was a smooth and logical flow from one topic to the next making each bit of information easy to digest for even a novice user of Kubernetes. I only had tiny issues with the guide, one being the way some links were provided e.g. "To learn about the various Kubernetes resources that you can configure, see the https://kubernetes.io/docs/concepts/." the ending of this sentence just sounds awkward. Instead of "see the <link>" perhaps just hyperlink it. This wasn't a common issue throughout the guide, I had little to no issue with how most links were provided, but by hyperlinking you might be able to give the guide a cleaner appearance. My only other issue was the separation of environments. The guide tells you if you are on Mac or Windows use Docker and if you are on Linux use Minikube. It would probably be more logical to separate these by Docker and Minikube and not operating system as I was able to complete the guide smoothly on MacOS with both Minikube and Docker. The guide should allow the user to use the technology that they feel is suitable and not limit them by OS especially when both technologies work on the OS. Besides those small issues I had a great experience and I was able to complete the guide in around 25 minutes.

**Comment by proubatsis** [comment] 2018-10-01 12:42
@evelinec @yeekangc We've talked about separating by MiniKube/DockerDesktop rather than by OS before, and the conclusion was that it would be better to separate by operating system. Is this still what we want to do, or does this feedback change your thoughts on it?

**Comment by yeekangc** [comment] 2018-10-01 13:51
I do believe we can have both mentioned i.e. separate by platforms and also indicate that it is Minikube or Docker Desktop.  The issue is that Docker Desktop is not everywhere.  And, what we have for Minikube may be specific to Linux only.

@gkwan-ibm

**Comment by gkwan-ibm** [comment] 2018-10-01 14:11
If I am fresh to Docker and Kubernetes, I do not know what Docker Desktop and Minikube are. It will be great for someone recommending me which is better to use in my computer. If I am familiar with them, I know which to use. I will realize "Is the guide described  correct or not?" 

IMO, I prefer separating by OS.

**Comment by wojtczat** [comment] 2018-10-01 15:13
You can still run through this guide with minikube if you are on a mac so maybe just do "Linux | Mac" as well. I think you should at least be aware that you have both options.

**Comment by yeekangc** [comment] 2018-10-01 15:39
The consideration isn't with the instructions alone but also the prereq setup process.  That needs to be taken into account.

**Comment by justineechen** [comment] 2018-10-01 17:46
I like Option 3 as well. But my confusion with this part of the guide was that I couldn't tell when the LINUX instructions ended and the overall instructions began. So is it possible to section off the instructions that depend on environment even more? Maybe in a box or have a beginning line / end line in gray?

**Comment by evelinec** [comment] 2018-10-01 18:21
Perhaps we can still add a sentence at the end of the prereqs section to say something like: If you are working on Windows or Mac, follow the `WINDOWS | MAC` instructions. If You're working on Linux environment, follow the "LINUX" instructions.

**Comment by proubatsis** [comment] 2018-10-01 18:56
I like that suggestion @evelinec , how does this sound?

```
Please note that while Minikube is also available on Mac and Windows, we discourage using it for the purposes of this guide since Docker Desktop provides a simplified setup process on Mac and Windows.
```

**Comment by proubatsis** [comment] 2018-10-01 19:21
Feedback addressed in #50 
Please review @evelinec and @wojtczat

**Comment by proubatsis** [comment] 2018-10-01 19:28
Thank you @yeekangc , I updated the wording accordingly in the PR.

**Comment by proubatsis** [comment] 2018-10-01 20:45
The proposal is implemented in these PRs: https://github.com/OpenLiberty/draft-guide-kubernetes/pull/50 and https://github.com/OpenLiberty/guides-common/pull/178

Let me know if these are in line with what we want or if we should go for something else.

**Comment by evelinec** [comment] 2018-10-02 04:06
Opened this issue https://github.com/OpenLiberty/guides-common/issues/179 to get improvement for the system text box to make the separation more obvious.

**Comment by evelinec** [comment] 2018-10-02 04:13
The system specific instructions are accurate and clear, we should not add additional tags that potentially causes more confusion. This means, no option 3 changes for the kube guide(s).

**Comment by proubatsis** [comment] 2018-10-02 12:41
Ready for review @wojtczat @evelinec : https://github.com/OpenLiberty/draft-guide-kubernetes/pull/50

**Comment by proubatsis** [comment] 2018-10-02 13:18
PR Merged.

**Closed by proubatsis** 2018-10-02 13:18 UTC
